import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  console.log(session?.user);
  return (
    <html lang="fr">
      <body className={inter.className}>
        <nav>{!!session && <span>je suis connecté</span>}</nav>
        <nav>{!session && <span>je suis déconnecté</span>}</nav>
        {children}
      </body>
    </html>
  );
}
